config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'
  resources :lists
  resources :tasks, except: [:index]
  get 'change/change_status'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :tasks, dependent: :destroy
  accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/change_controller.rb
class ChangeController < ApplicationController

  def change_status
    @task = Task.find(params[:id])
    helpers.change_complete(@task)
    redirect_to list_path(@task.list_id), success: "Task successfully update"
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
    
  def new
    @list = List.new
    @list.tasks.build
  end
  
  def index
    @lists = List.all.order(created_at: :desc)
  end
  
  def show
  end
  
  def edit
  end
  
  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list, success: "List successfully create"
    else
      render 'new', danger: "List not updated"
    end
  end
  
  def update
    if @list.update(list_params)
      redirect_to @list, success: "List successfully update"
    else
      render 'edit', danger: "List not updated"
    end
  end
  
  def destroy
    @list.destroy
    redirect_to lists_path, danger: "List successfully delete"
  end
  
  private
  
  def list_params
    params.require(:list).permit(:name, tasks_attributes: [:id, :title, :complete, :_destroy])
  end

  def set_list
    @list = List.find(params[:id])
  end
      
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def new
    @task = Task.new
    @list = List.find(params[:list_id])
  end
  
  def show
    @list = List.find(@task.list_id)
  end
  
  def edit
  end
  
  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to @task, success: "Task successfully create"
    else
      render 'new', danger: "Task not updated"
    end
  end
  
  def update
    if @task.update(task_params)
      redirect_to @task, success: "Task successfully update"
    else
      render 'edit', danger: "Task not updated"
    end
  end
  
  def destroy
    @list = List.find(@task.list_id)
    @task.destroy
    redirect_to list_path(@list), danger: "Task successfully delete"
  end
  
  private
  
  def task_params
    params.require(:task).permit(:title, :description, :complete, :list_id)
  end

  def set_task
    @task = Task.find(params[:id])
  end    
end

app/helpers/application_helper.rb
module ApplicationHelper
    def change_complete(task)
      if task.complete
        task.update_attributes(complete: false)
      else
        task.update_attributes(complete: true)
      end
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.slim
= simple_form_for(@list, html: { class: 'form-group' }) do |f|
  = f.input :name, placeholder: 'name', error: 'name is mandatory, please specify one'
  h3 Tasks
  #tasks
    = f.simple_fields_for :tasks do |task|
      = render 'task_fields', f: task
    .links
      = link_to_add_association 'add task', f, :tasks
  = f.submit class: 'btn btn-success'

app/views/lists/_task_fields.html.slim
.nested-fields
  = f.input :title
  = f.input :description, as: :text
  = f.input :complete, as: :boolean
  = link_to_remove_association "remove task", f

app/views/lists/edit.html.slim
h1 Editing List
= render 'form'
= link_to 'Back', lists_path, class: 'btn btn-success'

app/views/lists/index.html.slim
.container
  h1 Lists
  br/
  = link_to 'New List',  new_list_path, class: 'btn btn-success'
  br/
  br/
  table.table.table-hover.table-dark
    tr
      th Name
      th Actions
    - @lists.each do |list|
      tr
        td= list.name
        td
          = link_to 'Show', list_path(list), class: 'btn btn-success'
          = link_to 'Edit', edit_list_path(list), class: 'btn btn-primary'
          = link_to 'Destroy', list_path(list),            \
              method: :delete,                                             \
              data: { confirm: 'Are you sure?' } , class: 'btn btn-danger'

app/views/lists/new.html.slim
h1 New List
= render 'form'
= link_to 'Back', lists_path, class: 'btn btn-success'

app/views/lists/show.html.slim
.container
  br/
  h1.text-center = @list.name
  br/
  br/
  = link_to 'New Task', new_task_path(list_id: @list),class: 'btn btn-success'
  br/
  br/
  -if @list.tasks.present?
    table.table.table-hover.table-dark
      tr
        th Title
        th Description
        th Complete?
        th Change status
        th Actions
      - @list.tasks.order(created_at: :desc).each do |task|
        tr
          td= task.title
          td= task.description
          td= task.complete
          td= link_to 'Change', change_change_status_path(id: task), class: 'btn btn-warning mx-1'
          td
            = link_to 'Show', task_path(task), class: 'btn btn-success'
            = link_to 'Edit', edit_task_path(task), class: 'btn btn-success mx-1'
            = link_to 'Destroy', task_path(task),
              method: :delete,
              data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
  p.text-center
    = link_to 'Back', lists_path, class: 'btn btn-success mx-1'
    = link_to 'Edit', edit_list_path(@list), class: 'btn btn-success mx-1'
    = link_to 'Destroy', list_path(@list),
      method: :delete,
      data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

app/views/tasks/_edit_form.html.slim
= simple_form_for @task do |f|
  = f.input :title, input_html: { class: 'special' }
  = f.input :description, as: :text
  = f.input :complete, input_html: { value: '1' }
  = f.submit class: 'btn btn-success mb-3'

app/views/tasks/_form.html.slim
= simple_form_for @task do |f|
  = f.input :title, input_html: { class: 'special' }
  = f.input :description, as: :text
  = f.input :complete, input_html: { value: '1' }
  = f.hidden_field :list_id, value: @list.id
  = f.submit class: 'btn btn-success mb-3'

app/views/tasks/edit.html.slim
h1 Editing Task
= render 'edit_form'
= link_to 'Back', list_path(@task.list_id), class: 'btn btn-success'

app/views/tasks/new.html.slim
h1 New Task
= render 'form'
= link_to 'Back', list_path(@list), class: 'btn btn-success'

app/views/tasks/show.html.slim
.container.text-center
  br/
  strong Title:
  = @task.title
  br/
  br/
  strong Description:
  = @task.description
  br/
  br/
  strong Completed?:
  = @task.complete
  br/
  br/
  = link_to 'Back', list_path(@list), class: 'btn btn-success mx-1'
  = link_to 'Edit', edit_task_path(@task), class: 'btn btn-success mx-1'
  = link_to 'Destroy', task_path(@task),
    method: :delete,
    data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'